  
#全服公告
msg: '恭喜{player}抽到了{msg}'
not-key: '&c你没有开该宝箱的钥匙'
#在遍历背包的时候需要跳过的位置列表
#即不会判断列表内位置的物品是否是钥匙
skip-slot: []
#奖品列表
case:
  #自定义箱子id
  宝箱1:
    #lore中包含才会判定为该宝箱类型
    lore-contain: '1级宝箱'
    #能打开该宝箱的钥匙lore包含
    key-contain: '1级钥匙'
    #如果一个物品有多个宝箱的lore,则会判断该优先级,值越大优先级越高
    priority: 10
    #奖励列表   
    prize:
      #自定义奖品id
      奖品1:
        #奖品的名称
        msg: "一等奖"
        #执行的指令列表
        cmds:
        - 'say 我抽到了1等奖~~~~'
        #权重
        weight: 1
      #自定义奖品id
      奖品2:
        #奖品的名称
        msg: "二等奖"
        #执行的指令列表
        cmds:
        - 'say 我抽到了2等奖~~~~'
        #权重
        weight: 1
      #自定义奖品id
      奖品3:
        #奖品的名称
        msg: "三等奖"
        #执行的指令列表
        cmds:
        - 'say 我抽到了3等奖~~~~'
        #权重
        weight: 1
      #自定义奖品id
      奖品4:
        #奖品的名称
        msg: "安慰奖"
        #执行的指令列表
        cmds:
        - 'say 我抽到了安慰奖~~~~'
        #权重
        weight: 1
  #自定义箱子id
  宝箱2:
    #lore中包含才会判定为该宝箱类型
    lore-contain: '2级宝箱'
    #能打开该宝箱的钥匙lore包含
    key-contain: '2级钥匙'
    #如果一个物品有多个宝箱的lore,则会判断该优先级,值越大优先级越高
    priority: 9
    #奖励列表
    prize:
      #自定义奖品id
      奖品1:
        #奖品的名称
        msg: "嘻哈奖"
        #执行的指令列表
        cmds:
        - 'say 我抽到了嘻哈奖~~~~'
        #权重
        weight: 1